language: node_js
node_js:
        - "8"
branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
    directories:
        - "node_modules"

install:
  - npm i -g webpack

before_script:
  - openssl aes-256-cbc -a -d -in key.pem.enc -out key.pem -k $ENC_KEY

script:
  - bash ./deploy.sh
